-- ----------------------------
-- View structure for v_customer_list
-- ----------------------------
CREATE ALGORITHM=UNDEFINED DEFINER=`user`@`%` SQL SECURITY DEFINER VIEW `v_customer_list` AS select `t`.`customer_id` AS `customer_id`,`t`.`cust_name` AS `cust_name`,`t`.`cust_code` AS `cust_code`,`t`.`industry_name` AS `industry_name`,`t`.`address` AS `address`,`t`.`sys_company_user_id` AS `sys_company_user_id`,`t`.`sys_company_user_name` AS `sys_company_user_name`,`t`.`is_primary_csur` AS `is_primary_csur`,group_concat(cast(`cc`.`id` as char charset utf8) order by `cc`.`id` ASC separator ',') AS `contact_id`,group_concat(cast(`cc`.`name` as char charset utf8) order by `cc`.`id` ASC separator ',') AS `contact_name`,group_concat(cast(`cc`.`is_primary` as char charset utf8) order by `cc`.`id` ASC separator ',') AS `is_primary_contact` from (`v_customer_list_a` `t` left join `customer_contact` `cc` on((`t`.`customer_id` = `cc`.`customer_id`))) group by `t`.`customer_id`;

-- ----------------------------
-- View structure for v_customer_list_a
-- ----------------------------
CREATE ALGORITHM=UNDEFINED DEFINER=`user`@`%` SQL SECURITY DEFINER VIEW `v_customer_list_a` AS select `cust`.`id` AS `customer_id`,`cust`.`cust_name` AS `cust_name`,`cust`.`cust_code` AS `cust_code`,`ci`.`name` AS `industry_name`,concat(concat(`cust`.`country`,`cust`.`province`),concat(`cust`.`city`,`cust`.`address`)) AS `address`,group_concat(cast(`scu`.`id` as char charset utf8) order by `scu`.`id` ASC separator ',') AS `sys_company_user_id`,group_concat(cast(`scu`.`name` as char charset utf8) order by `scu`.`id` ASC separator ',') AS `sys_company_user_name`,group_concat(cast(`csur`.`is_primary` as char charset utf8) order by `csur`.`sys_company_user_id` ASC separator ',') AS `is_primary_csur` from (((`customer` `cust` join `customer_industry` `ci`) join `customer_sys_user_rel` `csur`) join `sys_company_user` `scu`) where ((`cust`.`industry_id` = `ci`.`id`) and (`cust`.`id` = `csur`.`customer_id`) and (`csur`.`sys_company_user_id` = `scu`.`id`)) group by `cust`.`id`;
